name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        include:
          - os: macOS-latest
            output-name: pesonet-check
          - os: windows-latest
            output-name: pesonet-check.exe

    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master
      - run: pub get
      - run: mkdir build
      - run: dart2native bin/main.dart -v -o build/${{ matrix.output-name }}
      - run: chmode +x build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v1
        with:
          name: pesonet_check
          path: build
